export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const ADD_LOADING_MESSAGE = "ADD_LOADING_MESSAGE";
export const DELETE_LOADING_MESSAGE = "DELETE_LOADING_MESSAGE";

export const SET_AUTH = "SET_AUTH";
export const SET_APP_SETTINGS = "SET_APP_SETTINGS";
